spring.jackson.deserialization.fail-on-unknown-properties=true

# Consumer DB Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/ipl?verifyServerCertificate=false&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/ipl
spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.default_schema=ipl
spring.jpa.properties.hibernate.default_schema=ipl

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

serverName=localhost
serverPort=8080
server.contextPath=/ipl
#contextName=ipl-service
